load("@bazel_tools//tools/build_rules/go:def.bzl", "go_prefix", "go_library")

go_prefix("github.com/laramiel/bazel-example-golang-bare/")

go_library(
    name = "bare",
    srcs = [ "bare/bare.go" ],
    visibility = ["//visibility:public"],
)
